In [37]:
import numpy as np

In [48]:
# Input data
letters = {
 'A': np.array([[ 1,  1,  1, -1,  1,  1,  1,
                  1,  1, -1,  1, -1,  1,  1,
                  1,  1, -1,  1, -1,  1,  1,
                  1,  1, -1,  1, -1,  1,  1,
                  1, -1, -1, -1, -1, -1,  1,
                  1, -1,  1,  1,  1, -1,  1,
                 -1,  1,  1,  1,  1,  1, -1,
                 -1,  1,  1,  1,  1,  1, -1]]),
    
 'B': np.array([[ 1, -1, -1, -1,  1,  1,  1,
                  1, -1,  1, -1,  1,  1,  1,
                  1, -1,  1, -1,  1,  1,  1,
                  1, -1, -1, -1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1, -1, -1, -1,  1,  1]]),
    
 'C': np.array([[ 1,  1, -1, -1, -1,  1,  1,
                  1, -1,  1,  1,  1, -1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1, -1,  1,
                  1,  1, -1, -1, -1,  1,  1]]),
    
 'D': np.array([[ 1, -1, -1, -1,  1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1, -1, -1,  1,  1,  1]]),
    
 'E': np.array([[ 1,  1, -1, -1, -1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1, -1, -1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1, -1, -1,  1,  1]]),
    
 'F': np.array([[ 1,  1, -1, -1, -1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1, -1, -1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1,
                  1,  1, -1,  1,  1,  1,  1]]),

 'G': np.array([[ 1,  1, -1, -1,  1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1,  1, -1, -1, -1,  1,  1]]),
    
 'H': np.array([[ 1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1, -1, -1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1]]),
    
 'I': np.array([[ 1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1,  1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1]]),
    
 'K': np.array([[ 1, -1,  1,  1, -1,  1,  1,
                  1, -1,  1, -1,  1,  1,  1,
                  1, -1,  1, -1,  1,  1,  1,
                  1, -1, -1,  1,  1,  1,  1,
                  1, -1, -1,  1,  1,  1,  1,
                  1, -1,  1, -1,  1,  1,  1,
                  1, -1,  1, -1,  1,  1,  1,
                  1, -1,  1,  1, -1,  1,  1]]),
    
 'L': np.array([[ 1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1,  1,  1,  1,  1,  1,
                  1, -1, -1, -1, -1,  1,  1]]),
    
 'T': np.array([[-1, -1, -1, -1 ,-1, -1, -1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1,
                  1,  1,  1, -1,  1,  1,  1]])
}

In [54]:
input_size = 7 * 8

# Calculate weights using input letters
W = np.zeros((input_size, input_size), dtype=np.int32)
for letter in letters.values():
    W = W + np.matmul(letter.transpose(), letter)

# Set diagonal elements to 0s
for i in range(input_size):
    W[i][i] = 0
    
W = W / len(letters)

W

array([[ 0.        ,  0.16666667,  0.        , ..., -0.33333333,
         0.83333333,  0.66666667],
       [ 0.16666667,  0.        , -0.16666667, ...,  0.16666667,
         0.        , -0.16666667],
       [ 0.        , -0.16666667,  0.        , ...,  0.        ,
        -0.16666667, -0.33333333],
       ...,
       [-0.33333333,  0.16666667,  0.        , ...,  0.        ,
        -0.16666667, -0.33333333],
       [ 0.83333333,  0.        , -0.16666667, ..., -0.16666667,
         0.        ,  0.83333333],
       [ 0.66666667, -0.16666667, -0.33333333, ..., -0.33333333,
         0.83333333,  0.        ]])

In [56]:
A = letters['A']

max_iterations = 1_000_000
iteration = 0
previous_result = None
result = A.transpose()

while (iteration < max_iterations) and not ((previous_result is not None) and (np.array_equal(result, previous_result))):
    previous_result = result
    result = np.int32(np.sign(np.matmul(W, result)))
    iteration += 1

print(iteration)
print(result.transpose())
print(A)

5
[[ 1 -1 -1 -1  1  1  1  1 -1  1  1  1  1  1  1 -1  1  1  1  1  1  1 -1  1
   1  1  1  1  1 -1  1  1  1  1  1  1 -1  1  1  1  1  1  1 -1  1  1  1  1
   1  1 -1 -1 -1 -1  1  1]]
[[ 1  1  1 -1  1  1  1  1  1 -1  1 -1  1  1  1  1 -1  1 -1  1  1  1  1 -1
   1 -1  1  1  1 -1 -1 -1 -1 -1  1  1 -1  1  1  1 -1  1 -1  1  1  1  1  1
  -1 -1  1  1  1  1  1 -1]]


In [19]:
a = np.array([[1, -1]])
np.matmul(a.transpose(), a)

array([[ 1, -1],
       [-1,  1]])

In [46]:
X1 = np.array([[1, -1, -1, 1]])

W = np.matmul(X1.transpose(), X1)

distorted = np.array([[1, 1, -1, 1]])

np.matmul(W, distorted.transpose())

array([[ 2],
       [-2],
       [-2],
       [ 2]])